#!/bin/bash -l
#
#SBATCH --job-name=COSC3500_Debug
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --time=0-00:05:00
#SBATCH --gres=gpu:1
#SBATCH --partition=cosc3500
#SBATCH --account=cosc3500

# module load compiler-rt/latest
# module add mkl/latest
# module add mpi/openmpi-x86_64
# module load cuda/11.1
# 
# #I would have expected the module loads to add these, but apparently not
# export PATH=/opt/local/stow/cuda-11.1/bin:$PATH
# export PATH=/usr/lib64/openmpi/bin:$PATH

make clean
make run
hostname
#"map-by node" (assigns processes per node. i.e. to make sure they're running on separate nodes, not all on the same node)
#"bind-to none" (for whatever reason, by default mpiexec will lock to a single core (i.e. single-threaded), bind-to none means the mpi process is free to use whatever cores it wants)

# time mpiexec -n 1 -map-by node -bind-to none
time ./run 1000 10 11 12 13 14 15 16
