#!/bin/bash -l
#
#SBATCH --job-name=COSC3500_Debug
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=0-00:05:00
#SBATCH --partition=cosc3500
#SBATCH --account=cosc3500

# module load compiler-rt/latest
# module add mkl/latest
module add mpi/openmpi-x86_64

export PATH=/usr/lib64/openmpi/bin:$PATH

make clean && make run && hostname && time ./run 1000 10 11 12 13 14 15 16
